// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.5
// source: casbin.proto

package message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CasbinInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path   string `protobuf:"bytes,1,opt,name=Path,proto3" json:"Path,omitempty"`
	Method string `protobuf:"bytes,2,opt,name=Method,proto3" json:"Method,omitempty"`
}

func (x *CasbinInfo) Reset() {
	*x = CasbinInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_casbin_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CasbinInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CasbinInfo) ProtoMessage() {}

func (x *CasbinInfo) ProtoReflect() protoreflect.Message {
	mi := &file_casbin_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CasbinInfo.ProtoReflect.Descriptor instead.
func (*CasbinInfo) Descriptor() ([]byte, []int) {
	return file_casbin_proto_rawDescGZIP(), []int{0}
}

func (x *CasbinInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CasbinInfo) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

type CasbinInReceive struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleId         string        `protobuf:"bytes,1,opt,name=RoleId,proto3" json:"RoleId,omitempty"`                 // 角色id
	ExtendsRoleIds []string      `protobuf:"bytes,2,rep,name=ExtendsRoleIds,proto3" json:"ExtendsRoleIds,omitempty"` //继承角色id
	CasbinInfos    []*CasbinInfo `protobuf:"bytes,3,rep,name=CasbinInfos,proto3" json:"CasbinInfos,omitempty"`
}

func (x *CasbinInReceive) Reset() {
	*x = CasbinInReceive{}
	if protoimpl.UnsafeEnabled {
		mi := &file_casbin_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CasbinInReceive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CasbinInReceive) ProtoMessage() {}

func (x *CasbinInReceive) ProtoReflect() protoreflect.Message {
	mi := &file_casbin_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CasbinInReceive.ProtoReflect.Descriptor instead.
func (*CasbinInReceive) Descriptor() ([]byte, []int) {
	return file_casbin_proto_rawDescGZIP(), []int{1}
}

func (x *CasbinInReceive) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *CasbinInReceive) GetExtendsRoleIds() []string {
	if x != nil {
		return x.ExtendsRoleIds
	}
	return nil
}

func (x *CasbinInReceive) GetCasbinInfos() []*CasbinInfo {
	if x != nil {
		return x.CasbinInfos
	}
	return nil
}

type PolicyPathResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Paths []*CasbinInfo `protobuf:"bytes,1,rep,name=Paths,proto3" json:"Paths,omitempty"`
}

func (x *PolicyPathResponse) Reset() {
	*x = PolicyPathResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_casbin_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PolicyPathResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyPathResponse) ProtoMessage() {}

func (x *PolicyPathResponse) ProtoReflect() protoreflect.Message {
	mi := &file_casbin_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyPathResponse.ProtoReflect.Descriptor instead.
func (*PolicyPathResponse) Descriptor() ([]byte, []int) {
	return file_casbin_proto_rawDescGZIP(), []int{2}
}

func (x *PolicyPathResponse) GetPaths() []*CasbinInfo {
	if x != nil {
		return x.Paths
	}
	return nil
}

var File_casbin_proto protoreflect.FileDescriptor

var file_casbin_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x63, 0x61, 0x73, 0x62, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x38, 0x0a, 0x0a, 0x43, 0x61, 0x73, 0x62, 0x69,
	0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x50, 0x61, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x4d, 0x65, 0x74,
	0x68, 0x6f, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x4d, 0x65, 0x74, 0x68, 0x6f,
	0x64, 0x22, 0x88, 0x01, 0x0a, 0x0f, 0x43, 0x61, 0x73, 0x62, 0x69, 0x6e, 0x49, 0x6e, 0x52, 0x65,
	0x63, 0x65, 0x69, 0x76, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x26, 0x0a,
	0x0e, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x73, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0e, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x73, 0x52, 0x6f,
	0x6c, 0x65, 0x49, 0x64, 0x73, 0x12, 0x35, 0x0a, 0x0b, 0x43, 0x61, 0x73, 0x62, 0x69, 0x6e, 0x49,
	0x6e, 0x66, 0x6f, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x2e, 0x43, 0x61, 0x73, 0x62, 0x69, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x0b, 0x43, 0x61, 0x73, 0x62, 0x69, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x22, 0x3f, 0x0a, 0x12,
	0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x50, 0x61, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x29, 0x0a, 0x05, 0x50, 0x61, 0x74, 0x68, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x13, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x43, 0x61, 0x73, 0x62,
	0x69, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x50, 0x61, 0x74, 0x68, 0x73, 0x42, 0x0c, 0x5a,
	0x0a, 0x2e, 0x2e, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_casbin_proto_rawDescOnce sync.Once
	file_casbin_proto_rawDescData = file_casbin_proto_rawDesc
)

func file_casbin_proto_rawDescGZIP() []byte {
	file_casbin_proto_rawDescOnce.Do(func() {
		file_casbin_proto_rawDescData = protoimpl.X.CompressGZIP(file_casbin_proto_rawDescData)
	})
	return file_casbin_proto_rawDescData
}

var file_casbin_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_casbin_proto_goTypes = []interface{}{
	(*CasbinInfo)(nil),         // 0: message.CasbinInfo
	(*CasbinInReceive)(nil),    // 1: message.CasbinInReceive
	(*PolicyPathResponse)(nil), // 2: message.PolicyPathResponse
}
var file_casbin_proto_depIdxs = []int32{
	0, // 0: message.CasbinInReceive.CasbinInfos:type_name -> message.CasbinInfo
	0, // 1: message.PolicyPathResponse.Paths:type_name -> message.CasbinInfo
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_casbin_proto_init() }
func file_casbin_proto_init() {
	if File_casbin_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_casbin_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CasbinInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_casbin_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CasbinInReceive); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_casbin_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PolicyPathResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_casbin_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_casbin_proto_goTypes,
		DependencyIndexes: file_casbin_proto_depIdxs,
		MessageInfos:      file_casbin_proto_msgTypes,
	}.Build()
	File_casbin_proto = out.File
	file_casbin_proto_rawDesc = nil
	file_casbin_proto_goTypes = nil
	file_casbin_proto_depIdxs = nil
}
